Don't replace LKL crashes with ABRT crashes.
google/clusterfuzz pull request #2146
Opened 2020-11-13 03:50 UTC by mspectorgoogle

The libfuzzer portion of the LKL stack may contain an ABRT don't replace
the crash_type similar to other aborts.

2020-11-13 03:50 UTC, mspectorgoogle commented
/gcbrun

2020-11-13 04:15 UTC, oliverchang requested changes

2020-11-13 04:15 UTC, oliverchang commented on src/python/crash_analysis/crash_analyzer.py
> +  if not is_lkl and has_signal_for_non_security_bug_type(crash_stacktrace):
this makes the logic a bit difficult to follow, and couples this code to lkl which is not ideal. We should just be relying on the crash_type and other testcase information here. 

What's the crash type for these bugs? Is it 'Kernel failure' ? Can you just add a crash_type check above to return True?

2020-11-13 04:15 UTC, oliverchang commented on src/python/lib/clusterfuzz/stacktraces/__init__.py
> +      # replace it with the ASSERT.
This comment seems a bit confusing. This isn't replacing anything with 'ASSERT'? 

Also can make this comment more general. Something along the lines of: "If we have a Go, Python, or Kernel crash, don't replace this with sanitizer signal handler failures."

2020-11-13 04:43 UTC, mspectorgoogle commented
/gcbrun

2020-11-13 04:47 UTC, oliverchang approved these changes

2020-11-13 04:47 UTC, oliverchang commented on src/python/crash_analysis/crash_analyzer.py
> +  if (not crash_type.startswith('Kernel failure') and
Can we just separate this out into a 
```python
# Assume kernel crashes are security bugs.
if crash_type.startswith('Kernel failure'):
  return True
```

above?

2020-11-13 05:12 UTC, mspectorgoogle commented
/gcbrun

2020-11-13 05:19 UTC, oliverchang approved these changes

2020-11-14 00:29 UTC, inferno-chromium approved these changes

2020-11-14 00:29 UTC, merged