Upload kcov data at end of syzkaller fuzz run.
google/clusterfuzz pull request #2249
Opened 2021-02-18 09:11 UTC by mspectorgoogle

Uploads the coverfile to coverage.reports.bucket at the end of the
fuzzing session.

2021-02-18 09:11 UTC, mspectorgoogle commented
/gcbrun

2021-02-19 02:43 UTC, oliverchang approved these changes
LGTM, but could you please fix the lint issues? (even if they are directly related to your PR). 

Thanks!

2021-02-19 02:43 UTC, oliverchang commented on src/python/bot/fuzzers/syzkaller/runner.py
> +  identifier = environment.get_value('BOT_NAME') + str(utils.utcnow())
also isoformat() here.

2021-02-25 05:29 UTC, mspectorgoogle commented
/gcbrun

2021-02-25 19:38 UTC, inferno-chromium requested changes
Please fix the lint failures as well, and these comments, can then merge.

Running: pylint src/python/bot/fuzzers/syzkaller/runner.py
| ************* Module src.python.bot.fuzzers.syzkaller.runner
| src/python/bot/fuzzers/syzkaller/runner.py:105:4: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
| src/python/bot/fuzzers/syzkaller/runner.py:110:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

2021-02-25 19:38 UTC, inferno-chromium commented on src/local/butler/run_bot.py
> +    if os.environ['OS_OVERRIDE'] != 'ANDROID_KERNEL':
This will exception if OS_OVERRIDE is not set
Probably just 
if not os.getenv('OS_OVERRIDE'):

2021-02-25 19:38 UTC, inferno-chromium commented on src/python/bot/fuzzers/syzkaller/runner.py
> +def _upload_kcov(kcov_path, kernel_bid):
_upload_kernel_coverage_data to make it clear ?

2021-02-26 05:03 UTC, mspectorgoogle commented
/gcbrun

2021-02-26 05:07 UTC, mspectorgoogle commented
/gcbrun

2021-02-26 05:27 UTC, merged